---
title: "Milestone 4"
author: "Chloe Shawah"
date: "10/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE)
library(tidyverse)
library(readr)
library(janitor)
```

```{r Data Readin}

#Read in data from "raw-data" directory and clean names

school_directory <- read.csv("raw-data/Education_Directory.csv") %>% 
  clean_names()
district_enrollment <- read.csv("raw-data/District_Enrollment_2013-14.csv") %>% 
  clean_names()
SAT_performance <- read_csv("raw-data/SAT_School_Participation_and_Performance_2012-2013.csv") %>% 
  clean_names()
```

```{r Clean data}

#Use "directory" dataframe as a base for seeing districts, etc.
#Filter for high schools

directory <- school_directory %>% 
  filter(grade_12 == 1) %>% 
  select(school_name, organization_code, organization_type, district_name) %>% 
  na.omit()

#Clean SAT data

SAT_by_enrollment <- SAT_performance %>% 
  select(school, percent_meeting_benchmark_2013)

#Clean enrollment data

enrollment <- district_enrollment %>% 
  select(district_name, total)

# Join 3 dataframes together using school names and district names
  
SAT_by_enrollment <- inner_join(directory, SAT_by_enrollment, by = c("school_name" = "school"))
SAT_by_enrollment <- inner_join(SAT_by_enrollment, enrollment, by = c("district_name" = "district_name"))
```

```{r Graph data}

# Plot the data, add labels, and make the points sea green!

ggplot(data = SAT_by_enrollment) +
  geom_point(aes(x = total, y = percent_meeting_benchmark_2013), color = "lightseagreen") +
  labs(x = "District Enrollment", 
       y = "Percent of Studnets Meeting SAT Benchmark",
       title = "CT High Schools: SAT scores by District Size",
       subtitle = "Based on 2013 scores and enrollments")
```

